### PR TITLE
Restructure into multiple instances

### LINKED ISSUE #359: [DOC] - Move Community into a separate sidebar
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Docusaurus allows us to have "multiple sidebars": https://docusaurus.io/docs/2.2.0/sidebar/multiple-sidebars

Since our ["Community" docs](https://www.nebari.dev/docs/community) have grown a lot organically, it'll be nice to split this into a separate sidebar. It'll make docs navigation easier.

### Steps to Resolve this Issue

Move all Community pages under a separate sidebar section.

### PR DESCRIPTION
**Pull request by pavithraes**
## Reference Issues or PRs

Closes #359
Addresses #435 

This pull request:
* Moves the "Community" pages into a separate instance, with a separate sidebar
* Creates a new instance for Nebari Slurm docs
* Updates top navbar to mention new projects
* Misc clean-up and consistency fixes

## TODOs before merging

- [x] Verify internal links are not broken by this change

## Comments

* For reviewers:
  *  I suggest starting with the preview
  * Ref: https://docusaurus.io/docs/docs-multi-instance
* Merge the currently open PRs before this one. This PR affects many pages and might disrupt ongoing updates.

### CODE REVIEW

**Comment by viniciusdc** [comment]
Absolutely fantastic work, thanks @pavithraes :rocket:

**Comment by viniciusdc** [comment]
Hi @pavithraes do you mind if I take over the remaining changes this PR requires to be fully merged? aka. the conflicts above.

**Comment by pavithraes** [comment]
@viniciusdc - I've fixed the conflicts, please take a look when you get a chance :)

**Review by viniciusdc — APPROVED** [review]
LGTM, thanks @pavithraes

**Comment by viniciusdc** [comment]
I will hold this till tomorrow, to have proper time to review the child issues related to those changes as well

**Pull request merged**
