### PR TITLE
ENH -  Replace QHub -> Nebari

### PR DESCRIPTION
**Pull request by trallard**
- :pencil2: Minor fixes
- :wrench: Remove author from "last updated"
- :pencil2: Replace cloud providers URLs
- :pencil2: Replace QHub -> nebari
- :wrench: Remove announcement bar
- :pencil2: Update banner
- :pencil2: Fix capitalization

## Reference Issues or PRs

Closes: https://github.com/Quansight/qhub/issues/1444 

## What does this implement/fix?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [x] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [x] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [x] This content adheres to the Nebari style guides.

#### Non-text content

- [x] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If the content were to be read as plain text, it still makes sense, and no information is missing.

### CODE REVIEW

**Review by kcpevey — APPROVED** [review]
LGTM!

**Comment by trallard** [comment]
@trallard  to go and recapitalised

**Comment by trallard** [comment]
@pavithraes  this is ready for a last check - all seems to be building ok so feel free to approve and merge shall you deem it fit 💪🏽

**Comment by pavithraes** [comment]
Looks great, thank you for working on this!

**Pull request merged**
