### PR TITLE
Reorganize sidebar

### PR DESCRIPTION
**Pull request by kcpevey**
This PR reorganize the sidebar to group pages based on the user type they are targeting. This makes it easier for people to find the pages they are looking for. 

I've added `Platform Admins` and `Platform End User` sections to the `Getting Started`, `How Tos`, and `Tutorials`. I'd be happy to change those section labels if someone has a better suggestion. 

image

The `Getting Started` section did not have any content for end users (which is a miss) so I just added a duplicate link to the how tos for keycloak login and environment creation. Long term we need to think through what that _should_ look like - maybe add a quickstart?

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### CODE REVIEW

**Comment by viniciusdc** [comment]
Gorgeous!!! It looks much more organic now as well, at least in my humble opinion, Thanks @kcpevey :rocket:

**Comment by viniciusdc** [comment]
We will merge #476 first, as it's a structural change in how the plugins work, and then we can merge this one.

**Comment by viniciusdc** [comment]
Hi @kcpevey just as a followback, I will be merging this tomorrow after the 476, just today will be a bit complicated to get all ready after that merge.

**Comment by viniciusdc** [comment]
can you update this PR?

**Comment by kcpevey** [comment]
I talked to @pavithraes who has some good ideas related to this. We are going to hold off on merging until we make some changes.

**Comment by pavithraes** [comment]
@kcpevey Here's a proposal for the restructure, please let me know what you think. The notes that have "💬" are some inline comments.

Additionally, each page will have tags like "End-user", "Platform administrator", "Keycloak", etc., and these tags will be documented in the top-level pages like "**Administration how-to’s**.

---

[**Introduction**](https://www.nebari.dev/docs/tutorials/argo-workflows-walkthrough)

**Usage Tutorials**

- [Authenticate & Launch JLab](https://www.nebari.dev/docs/tutorials/login-keycloak)
- [Manage packages & environments](https://www.nebari.dev/docs/tutorials/creating-new-environments)
- [Create, deploy, and share dashboards and apps](https://www.nebari.dev/docs/tutorials/create-dashboard)
- [Work with big data using Dask](https://www.nebari.dev/docs/tutorials/using_dask)
- [Submit notebook jobs with Jupyter Scheduler](https://www.nebari.dev/docs/tutorials/jupyter-scheduler)
- [Argo workflows walkthrough](https://www.nebari.dev/docs/tutorials/argo-workflows-walkthrough)

**Usage how-to’s**

- [Using Visual Studio (VS) Code](https://nebari.dev/docs/how-tos/using-vscode)
- [Automate your first workflow with Argo](https://nebari.dev/docs/how-tos/using-argo)
- [JHub App Launcher with Nebari](https://nebari.dev/docs/how-tos/jhub-app-launcher)
- [Access system logs (Loki) via Grafana](https://nebari.dev/docs/how-tos/access-logs-loki)
- [Use GPUs on Nebari](https://nebari.dev/docs/how-tos/use-gpus)

**Administration how-to’s**

- [Quickstart](https://www.nebari.dev/docs/get-started/quickstart) (💬 Rename this to "deployment process overview", or "CLI Overview"? Since most users with setup Nebari only once, having quickstart is not as relevant as an overview, because folks will have to through most of the following pages to actually fully deploy Nebari)
- Initial deployment setup 
    - [Installing Nebari](https://www.nebari.dev/docs/get-started/installing-nebari)
    - [Setup Deployment Environment](https://nebari.dev/docs/how-tos/nebari-environment-management) (💬 Consider combining this with the previous install Nebari page?)
    - [Choosing a deployment platform](https://www.nebari.dev/docs/get-started/deploy)
    - [Setup Nebari domain registry](https://nebari.dev/docs/how-tos/domain-registry)
    - [Supported cloud providers](https://www.nebari.dev/docs/get-started/cloud-providers)
        - [Deploy Nebari on GCP](https://nebari.dev/docs/how-tos/nebari-gcp)
        - [Deploy Nebari on AWS](https://nebari.dev/docs/how-tos/nebari-aws)
        - [Deploy Nebari on Digital Ocean](https://nebari.dev/docs/how-tos/nebari-do)
        - [Deploy Nebari on Azure](https://nebari.dev/docs/how-tos/nebari-azure)
        - [How to deploy Nebari on pre-existing infrastructure](https://nebari.dev/docs/how-tos/nebari-kubernetes)
        - [Deploy Nebari on local machines (for testing)](https://nebari.dev/docs/how-tos/nebari-local)
- Configure Nebari
    - [Configure Keycloak](https://nebari.dev/docs/how-tos/configuring-keycloak)
    - [Advanced configuration](https://nebari.dev/docs/explanations/advanced-configuration)
    - [Security configuration](https://nebari.dev/docs/explanations/security-configuration)
    - [Cloud provider configuration](https://nebari.dev/docs/explanations/provider-configuration)
    - [Configure profiles](https://nebari.dev/docs/explanations/profile-configuration)
    - [Customize JupyterHub theme](https://nebari.dev/docs/explanations/customize-themes)
    - [Environment configurations](https://nebari.dev/docs/explanations/environments-configuration)
    - [Custom configurations and overrides](https://nebari.dev/docs/explanations/custom-overrides-configuration)
    - [Configuration best practices](https://nebari.dev/docs/explanations/config-best-practices)
    - [How to Set Up Monitoring on Nebari](https://nebari.dev/docs/how-tos/setup-monitoring)
    - [Telemetry](https://nebari.dev/docs/how-tos/telemetry)
    - [Set up Argo workflows](https://nebari.dev/docs/how-tos/setup-argo)
- Maintain your Nebari instance
    - [How to Set Up Monitoring on Nebari](https://nebari.dev/docs/how-tos/setup-monitoring)
    - [Upgrade Nebari](https://nebari.dev/docs/how-tos/nebari-upgrade)
    - [Upgrade cluster's Kubernetes version](https://nebari.dev/docs/how-tos/kubernetes-version-upgrade)
    - [Create a manual backup](https://nebari.dev/docs/how-tos/manual-backup)
    - [Debug Nebari deployment](https://nebari.dev/docs/how-tos/debug-nebari)
    - [Destroy your Nebari deployment](https://nebari.dev/docs/how-tos/nebari-destroy)
    - [Update JupyterHub idle-culling settings](https://nebari.dev/docs/how-tos/idle-culling)
- [Nebari Extension System](https://nebari.dev/docs/how-tos/nebari-extension-system)

**Conceptual guides**
- [Nebari Stages Directory](https://nebari.dev/docs/how-tos/nebari-stages-directory)

**References**
- [Release notes](https://www.nebari.dev/docs/references/RELEASE)
- [Troubleshooting](https://www.nebari.dev/docs/troubleshooting)
- [FAQs](https://www.nebari.dev/docs/faq)
- [User personas](https://www.nebari.dev/docs/references/personas) (💬 Shall we move this to the "Community" section?)

**Comment by kcpevey** [comment]
@pavithraes this is amazing! I love it! 

>Rename this to "deployment process overview", or "CLI Overview"?

I agree, I like "CLI Overview". 

>Consider combining this with the previous install Nebari page?

Yes definitely. Seems like that was a legacy page that doesn't add much value. We can pick out anything we want to keep and just add it to the "installing Nebari" page. 

>Shall we move this to the "Community" section

Sounds good to me!

**Comment by kcpevey** [comment]
Closing this one in favor of @pavithraes 's idea above.

**Pull request closed without merging**
