### PR TITLE
Change some landing page integrations

### LINKED ISSUE #217: Landing page integrations updates
### Context

Update integrations on the landing page:
* Replace Prefect with Argo
* Replace ClearML with CDS Dashboards or Jitsi

### Value and/or benefit

Prefect and ClearML integrations are not working reliably right now, so we can highlight some other working integrations.

We can add these back later when we're confident.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pavithraes**
## Reference Issues or PRs

Fixes #217

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Other (please describe): Design

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### CODE REVIEW

**Review by gabalafou — COMMENTED** [review]
I believe the ClearML and Prefect SVGs are no longer being used anywhere else, so can we delete them from the repo?

**Comment by pavithraes** [comment]
> I believe the ClearML and Prefect SVGs are no longer being used anywhere else, so can we delete them from the repo?

@gabalafou Thanks, done!

**Review by gabalafou — APPROVED** [review]

**Comment by trallard** [comment]
Were we meant to remove them altogether?

**Comment by pavithraes** [comment]
> Were we meant to remove them altogether?

Yes, for now, because they don't work well currently. We can add them back, alongside the current Argo and Jitsi logos, when we have better support. :)

(I still deleted the SVGs to keep the repo clean)

**Comment by trallard** [comment]
@pavithraes  this seems like it can be merged - if so can you merge this PR?

**Pull request merged**
