### PR TITLE
Add background decorations to landing page

### PR DESCRIPTION
**Pull request by gabalafou**
## Reference Issues or PRs

- https://github.com/nebari-dev/nebari-docs/issues/220

Note: there was no guidance from [the Figma](https://www.figma.com/file/48vtmwvvuw8OjRV6Gp9bk9/Nebari-website?node-id=2%3A1396&t=4Gr8ATrdO7J70wi1-0) about how these should behave at very narrow/mobile or very wide widths, so I just made some guesses. I need people to examine the preview page at various widths to make sure it looks good.

### CODE REVIEW

**Review by pavithraes — APPROVED** [review]

**Comment by pavithraes** [comment]
@gabalafou Thank you, this is looking really nice! ✨

A thought (that doesn't need to block merging this PR) -- the Nebari silhouette in the footer seems to be visually interfering with the Documentation column text on desktop sizes, and feels oddly large on medium/small width. I'd prefer updating or removing it.

@trallard What are your thoughts on this PR?

**Comment by gabalafou** [comment]
Thanks for the review @pavithraes. The footer is so far from the intended design, it should probably be handled in a separate pass. I went ahead and reverted the changes to the footer. I'll wait for the preview build, and then merge this in.

**Comment by gabalafou** [comment]
Actually I am going to make a few small tweaks from comments I got from Irina before merging this in, so stay tuned 🙂

**Comment by trallard** [comment]
Oooooo fancy ✨ 💅🏽  - out of curiosity I ran a Lighthouse test and it threw away that the `Get started` button (`#C118E4`) does not have enough contrast with the text (`#F1F1F6`) so could you sneak in that fix in the PR 🙏🏽 (`--nebari-magenta-3` should fix this)?

Observations for small screens/mobile:

1. The GIF becomes extremely hard to read/appreciate - not really sure what the best alternative would be. Filling the width of the screen?


Notification_Center


2. The hero banner has a golden circle on the right-top quadrant, as I was changing the screen width, I could see the circle move away towards the right until it disappears (it seems to be the only item doing that or at least obviously). It completely disappears at 1000px - it is not a big issue and perhaps only noticeable if one is resizing to catch any nags like this

Notification_Center

**Comment by gabalafou** [comment]
Thanks Tania for the review!

1. Accessibility / color contrast. This isn't related to this PR, so I will open another PR to address the color contrast issue specifically.
2. The GIF also isn't related to this PR, so I will open an issue for it.
3. This seems fine to me, but I defer to @Irinafumarel

**Comment by gabalafou** [comment]
1. #269 
2. #270

**Pull request merged**
