### PR TITLE
ENH - Update design assets

### PR DESCRIPTION
**Pull request by trallard**
- :memo: Add logo to README
- :memo: Update confusing wording
- :memo: Improve FAQ
- :pencil2: Minor fixes to faq
- :wrench: Remove empty sections for now
- :lipstick: Update fonts
- :bento: Add favicon

## Reference Issues or PRs

Fixes: #62 

## What does this implement/fix?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [x] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [x] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [x] This content adheres to the Nebari style guides.

#### Non-text content

- [x] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If the content were to be read as plain text, it still makes sense, and no information is missing.

### CODE REVIEW

**Review by costrouc — APPROVED** [review]
@trallard is there an easy way to see the preview? I see in this PR that there isn't a link to click on.

**Comment by costrouc** [comment]
Would it be possible to have the colors/font used in the designs to be posted somewhere as well? This would make it easier to create consistent themes other places e.g. in https://github.com/Quansight/qhub-jupyterhub-theme

**Comment by trallard** [comment]
Weird - the build was cancelled but here is the preview https://deploy-preview-143--nebari-docs.netlify.app/

As for colours + fonts + other design patterns I will add them all in the design repo https://github.com/nebari-dev/nebari-design

**Comment by costrouc** [comment]
@trallard makes sense and looks great to me thanks!

**Pull request merged**
