### PR TITLE
Tutorial on using vs code

### LINKED ISSUE #55: [DOC] How to setup and start working with VS Code on Nebari
The [current docs](https://docs.qhub.dev/en/stable/source/user_guide/code_server.html?highlight=vscode#in-browser-vscode) need to be expanded and migrated over to Nebari.

[notion](https://www.notion.so/quansightlabs/How-to-setup-and-start-working-with-vscode-7d6b196dffff47619b5432f0858613cc)

### PR DESCRIPTION
**Pull request by kcpevey**
Resolves #55 

* Show users how to use vscode

### CODE REVIEW

**Comment by kcpevey** [comment]
Blocked until vs code extension issue is worked out

**Comment by kcpevey** [comment]
The scss files were failing eslint because it didn't like the leading `.`. Based on [this issue in eslint](https://github.com/eslint/eslint/issues/11291), I've removed the checking of scss with eslint.

**Comment by kcpevey** [comment]
It would appear I inadvertently linted every doc... well i guesss it needed to happen anyway?

**Comment by kcpevey** [comment]
I'm not super happy with how the images are hard to discern from the word blocks. I tried to figure out to add a border, but I couldn't sort it out in a reasonable amount of time. Any advice on that @trallard ?

**Review by iameskild — APPROVED** [review]
It's appropriate that @kcpevey write the docs for the vscode extension 😉 

This looks good to me :)

**Comment by kcpevey** [comment]
Image formatting issue opened: https://github.com/nebari-dev/nebari-docs/issues/130

**Pull request merged**
